// Objets — 15 bases. Voir CONTRAT.md §6.
// Chaque description dit à quoi sert l'objet. Jamais de chiffre de règle.

export const objets = {
  "OBJ-01": {
    id: "OBJ-01",
    nom: "Arc de chasse",
    categorie: "arme",
    famille: "arc",
    poids: 2.0,
    degats: 7,
    protection: null,
    empilable: false,
    usable: true,
    description: "Il abat une proie à distance sans prévenir le reste du bois, tant qu'il reste des flèches.",
  },

  "OBJ-02": {
    id: "OBJ-02",
    nom: "Flèches à pointe d'os",
    categorie: "ressource",
    famille: null,
    poids: 0.05,
    degats: null,
    protection: null,
    empilable: true,
    usable: false,
    description: "Munitions de l'arc, qu'on récupère sur la bête quand la pointe a tenu.",
  },

  "OBJ-03": {
    id: "OBJ-03",
    nom: "Couteau de dépouille",
    categorie: "arme",
    famille: "lame_legere",
    poids: 0.6,
    degats: 4,
    protection: null,
    empilable: false,
    usable: true,
    description: "Lame courte pour ouvrir une bête, trancher une corde ou frapper quand l'autre est déjà sur vous.",
  },

  "OBJ-04": {
    id: "OBJ-04",
    nom: "Outre de cuir",
    categorie: "divers",
    famille: null,
    poids: 0.4,
    degats: null,
    protection: null,
    empilable: false,
    usable: true,
    capacite_eau: 3,
    description: "Elle décide de la quantité d'eau qu'on peut emporter d'une source à la suivante.",
  },

  "OBJ-05": {
    id: "OBJ-05",
    nom: "Eau de source",
    categorie: "consommable",
    famille: null,
    poids: 0.5,
    degats: null,
    protection: null,
    empilable: true,
    usable: false,
    description: "Une ration d'eau claire, à boire soi-même ou à donner.",
    effets_consommation: [
      { fatigue: -8 },
      { retire_etat: "assoiffe" },
    ],
  },

  "OBJ-06": {
    id: "OBJ-06",
    nom: "Viande fraîche",
    categorie: "consommable",
    famille: null,
    poids: 1.2,
    degats: null,
    protection: null,
    empilable: true,
    usable: false,
    perissable: 3,
    description: "La chasse du jour, qui cale un homme pour longtemps mais tourne vite par temps doux.",
    effets_consommation: [
      { faim: -40 },
    ],
  },

  "OBJ-07": {
    id: "OBJ-07",
    nom: "Épée de soldat",
    categorie: "arme",
    famille: "lame_longue",
    poids: 1.8,
    degats: 9,
    protection: null,
    empilable: false,
    usable: true,
    description: "Lame d'ordonnance, assez longue pour tenir un homme à distance de bras et assez maniable pour le bois.",
  },

  "OBJ-08": {
    id: "OBJ-08",
    nom: "Hache lourde",
    categorie: "arme",
    famille: "lourde",
    poids: 4.5,
    degats: 14,
    protection: null,
    empilable: false,
    usable: true,
    description: "Elle ouvre une garde ou une porte du premier coup, mais il faut l'armer et la porter toute la journée.",
  },

  "OBJ-09": {
    id: "OBJ-09",
    nom: "Épieu de chasse",
    categorie: "arme",
    famille: "hast",
    poids: 3.2,
    degats: 11,
    protection: null,
    empilable: false,
    usable: true,
    description: "La hampe garde la bête ou l'homme hors de portée tant qu'on a la place de la tenir droite.",
  },

  "OBJ-10": {
    id: "OBJ-10",
    nom: "Veste de cuir clouté",
    categorie: "protection",
    famille: null,
    poids: 2.5,
    degats: null,
    protection: 3,
    empilable: false,
    usable: true,
    description: "Cuir épais qui amortit les coups sans gêner la marche ni le tir.",
  },

  "OBJ-11": {
    id: "OBJ-11",
    nom: "Cotte de mailles",
    categorie: "protection",
    famille: null,
    poids: 6.0,
    degats: null,
    protection: 7,
    empilable: false,
    usable: true,
    description: "Maille de troupe : elle arrête presque tout et se fait sentir à chaque pas de côte.",
  },

  "OBJ-12": {
    id: "OBJ-12",
    nom: "Baume de plaie",
    categorie: "consommable",
    famille: null,
    poids: 0.2,
    degats: null,
    protection: null,
    empilable: true,
    usable: false,
    description: "Pâte de résine et de graisse qui referme une entaille et empêche qu'elle s'envenime.",
    effets_consommation: [
      { sante_heros: 10 },
      { retire_etat: "blesse_leger" },
    ],
  },

  "OBJ-13": {
    id: "OBJ-13",
    nom: "Nécessaire de réparation",
    categorie: "ressource",
    famille: null,
    poids: 1.0,
    degats: null,
    protection: null,
    empilable: true,
    usable: false,
    description: "Boyau, lanières de cuir et pierre à aiguiser, de quoi remettre une arme en état de servir.",
  },

  "OBJ-14": {
    id: "OBJ-14",
    nom: "Corde et crochet",
    categorie: "divers",
    famille: null,
    poids: 1.5,
    degats: null,
    protection: null,
    empilable: false,
    usable: true,
    description: "Elle ouvre les descentes de dévers et les passages qu'on devrait sinon contourner.",
  },

  "OBJ-15": {
    id: "OBJ-15",
    nom: "Galettes de voyage",
    categorie: "consommable",
    famille: null,
    poids: 0.4,
    degats: null,
    protection: null,
    empilable: true,
    usable: false,
    description: "Vivres sèches qui tiennent au ventre et se gardent sans tourner.",
    effets_consommation: [
      { faim: -25 },
    ],
  },
};
